### ISSUE TITLE
ヘッダーコンポーネントを作る

### ISSUE THREAD

**Issue by Tomoya113** [lit-kansai/dj_system-portal#24]
これ！(共通する所を多いのでコンポーネントに切り出しましょう)
[image](https://user-images.githubusercontent.com/22112440/145408861-9dae65cf-ef49-4f2e-8982-250f3ae97126.png)

**Comment by Tomoya113** [comment]
@penguin4731 
MTGまでにこれお願いしていい？
(ネオン周りのクラスは`tailwind.config.js`にまとまっているので、ご参照ください)

**Comment by penguin4731** [comment]
https://github.com/Tomoya113/la-portfolio
一旦この感じ説？
