### ISSUE TITLE
【学習】Nuxtの勉強する

### ISSUE THREAD

**Issue by Tomoya113** [lit-kansai/dj_system-portal#4]

**Comment by Tomoya113** [comment]
[公式ドキュメント](https://nuxtjs.org/ja/)

**Comment by Tomoya113** [comment]
認証周り以外Vuexじゃなくてよさそう
Composition APIでReactのHooksみたいに出来るので、それでええんちゃう？

**Comment by Tomoya113** [comment]
https://github.com/axios/axios

**Comment by Tomoya113** [comment]
https://tomoya-tanaka.notion.site/DJ-System-Frontend-5e81136fb04e4ac08964a13ebaa5892a

**Comment by penguin4731** [comment]
- リクエストした時にどうやってヘッダ載せるかはわかった
- Notionにチラッとどんなディレクトリ構造でいこうか書いた
- Vuexが変動期でそろそろ型がつくみたい。
  - 文献もないので、利用はしない。

## 結論
- Nuxt 2.0
- Composition API
- ページ跨いで必要なところはVuexでつくる
- 大まかな指針が決まった
