### ISSUE TITLE
【デザイン】黄色ボタンのhover表現

### ISSUE THREAD

**Issue by penguin4731** [lit-kansai/dj_system-portal#47]
# 概要

【デザイン】黄色ボタンのhover表現

# 目的

デザイン大事

# タスク

- [ ] hover時の表現きめる

# 参考リンク

**Comment by penguin4731** [comment]
- ネオンでする？
- 回転させる？

**Comment by ayu129** [comment]
ベタ塗りじゃなくて、文字をネオンにする→hoverで枠線アニメーションとか...？
