### ISSUE TITLE
【デザイン】コンセプト決定

### ISSUE THREAD

**Issue by penguin4731** [lit-kansai/dj_system-portal#5]
スプシにトンマナを洗い出す！

**Comment by ayu129** [comment]
https://docs.google.com/presentation/d/1OFrh2kcXlN_YNL3oWcqTwBVPlW7e244-vop91sEVl3c/edit?usp=sharing

**Comment by penguin4731** [comment]
![スクリーンショット 2021-11-23 0 00 33](https://user-images.githubusercontent.com/57238213/142884098-d52baff1-8080-4f6a-aaa4-9f7e817db6e6.png)
